### ISSUE TITLE
ZK announcement path cannot be set by environment variables

### ISSUE THREAD

**Issue by justincely** [DecipherNow/gm-fabric-jvm#104]
The [docs](https://github.com/DecipherNow/gm-fabric-jvm/blob/master/documentation/AnnounceAndBind.md) let us set the hostname, and ports - but the ZK announcement path cannot be set through the environment.  This is probably the other most-changed config (different paths for different environments, as well as version number changes).

This was discussed offline already, and is not likely to be added at this time for reasons that @joshua-rutherford will probably elucidate below.  Tracking here for posterity.

**Comment by justincely** [comment]
@dborncamp to follow up from the zoom yesterday

**Comment by ghershfield** [comment]
@justincely @dborncamp @joshua-rutherford That is a ticket for me to fix; Only announcements of ports can be set via ENV.

**Comment by joshua-rutherford** [comment]
@ghershfield, this is not actionable right now.  We have work arounds in place but as we move forward we'll to be able to override all configuration variables from the environment variables (or in my estimation, from an external source).

**Comment by ghershfield** [comment]
@joshua-rutherford Well I actually started it on 0.2.3 ... own time.

**Comment by ghershfield** [comment]
- Resolved by Issue #99
