### ISSUE TITLE
Unable to upload files over 5.2 MB to service after converting to GM Fabric 0.2.2

### ISSUE THREAD

**Issue by adkirk25** [DecipherNow/gm-fabric-jvm#135]
Uploading file larger than 5.2 MB returns http response of "413 Request Entity Too Large" and there is an exception in the service log: `com.twitter.finagle - Unhandled exception in connection with ###.###.###:#### , shutting down connection java.lang.IllegalStateException: received HttpChunk without HttpMessage`

After turning on debug logging in service on start up in wrapper.log:
`[WrapperSimpleAppMain] DEBUG c.t.inject.app.internal.FlagsModule 97 --- Binding flag: maxRequestSize = 5242880.bytes` which is 5.24MB

We used to be able to set -com.twitter.finatra.config.maxRequestSize` in parameters.config but with GM Fabric that flag is not supported and causes the service to fail to start.

This file was successfully uploaded:
`-rw-r--r--  5178348 Feb 26 08:41 large500.txt`

This file did not upload:
```-rw-r--r--  5609877 Feb 26 08:45 large550.txt```

**Comment by lucasmoten** [comment]
Can parameters.config have the following set?
```
-com.twitter.finagle.Http.param.MaxRequestSize
```

**Comment by rfielding** [comment]
There are three separate places that impose this limit explicitly, and a few that impose it implicitly:

- max request size set in Finagle server getting a request (3MB default I believe.  It's small.)
- max request size set in Finagle client (similar)
- the nginx server.  fabric:1.0.4 had to be modified to bump up the limit.  maybe it's nginx.

For the Finagle server and nginx server, I believe that look at Content-Length and balk without trying to perform the action.  But keep in mind that with Finagle, you can't truly lift these limits.  If you are using a Finagle-based server, the memory consumption is going to be a multiple (5x?) of the size of all requests (and probably responses) happening concurrently.

This means that you may think you fixed it by pushing up a 20MB file as a test, but when the server is running under any kind of reasonable load, it can still run out of memory due to interleaved requests.

**Comment by adkirk25** [comment]
If the issue were nginx would we see any error in the service log?

**Comment by adkirk25** [comment]
`Wrapper code received an unknown packet type: -122
INFO   | jvm 5    | 2018/02/26 14:38:58 | Error parsing flag "com.twitter.finagle.Http.param.MaxRequestSize": flag undefined
INFO   | jvm 5    | 2018/02/26 14:38:58 | usage: gov.ic.dodiis.dctc.bedrock.WDDocumentCompositeService [<flag>...]`

**Comment by rfielding** [comment]
For my service that needs multi-GB requests and responses:


```
        client_max_body_size 0;                                                                                                                                                                                                
                                                                                                                                                                                                                               
        proxy_buffering off;                                                                                                                                                                                                   
        proxy_request_buffering off; 
```

**Comment by adkirk25** [comment]
We already had that configured the same way. Note that this was working before we upgraded to GM Fabric.
```
proxy_buffering off;
proxy_request_buffering off;
client_max_body_size 0;
```

**Comment by rfielding** [comment]
```
Wrapper code received an unknown packet type: -122 INFO | jvm 5 | 2018/02/26 14:38:58 | Error parsing flag "com.twitter.finagle.Http.param.MaxRequestSize": flag undefined INFO | jvm 5 | 2018/02/26 14:38:58 | usage: ....WDDocumentCompositeService [<flag>...]
```

Is that just a missing front-dash in 

```
-com.twitter.finagle.Http.param.MaxRequestSize
```
?

**Comment by rfielding** [comment]
@ghershfield

**Comment by adkirk25** [comment]
NO thats just the format of the error message, from the etc/parameters.config:

`-com.twitter.finagle.Http.param.MaxRequestSize=500`

**Comment by adkirk25** [comment]
I've tried about 4 different ways to set the flag and they all result in the error. I can't find any documentation for finagle or finatra on what flags are supported in the version we are using. I can see the finatra and finagle code both use the flags but cannot get passed the error.

`-com.twitter.finagle.http.param.MaxRequestSize`
`-com.twitter.finagle.http.Http.maxRequestSize`
`-com.twitter.finagle.config.maxRequestSize`
`-com.twitter.finatra.config.maxRequestSize`
