### ISSUE TITLE
Filter out static version numbers from metrics.json

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-jvm#146]
Currently, each microservice reports out version numbers for components each time metrics.json is requested. The payload could be slimmed down a bit by setting a filter as described below.

I'd filter these out:
* toggles
* finagle/build/revision

![image](https://user-images.githubusercontent.com/8700322/37920497-fad90670-30f4-11e8-9845-18922e96f676.png)

https://twitter.github.io/twitter-server/Features.html#metrics-label

**Comment by spmcbride1201** [comment]
I'm curious about what @joshua-rutherford and @lucasmoten think about this too.

**Comment by chrismholmes** [comment]
We are deprecating this part of the Grey Matter framework, so I would rather not spend too much time on this.

**Comment by spmcbride1201** [comment]
Closing because of our stated intention to deprecate this project.
