### ISSUE TITLE
Dockerized services announce container IP instead of host IP

### ISSUE THREAD

**Issue by justincely** [DecipherNow/gm-fabric-jvm#55]
Running the JVM services in docker containers automatically announce the internal docker IP to the zookeeper nodes.  We need to find a way to override the zk announcement host, or resolve how were deploying them if this is already a solved problem

@atoy3731 you can describe more of your issue here so we can resolve it.

**Comment by atoy3731** [comment]
If we containerize the service, the service would need to announce the host's IP and the host's port that the container's local port is forwarded to to Zookeeper instead of its internal IP/port.

We did do something similar to this to the CTE framework when we were experimenting with DCOS:  https://gitlab.363-283.io/cte/cte-service-framework/commit/1966f17a255f5516879b58aac86345af4ca452b2

That did the following:
1.  Added a new true/false setting to `parameters.config` for `docker.enabled`.
2. If `docker.enabled` was true, the framework would look for predefined environment variables for the host IP and the forwarded port and announce them to ZK.
3. If `docker.enabled` was false, the framework would continue functioning as it does now.
4. If `docker.enabled` was true but the environment variables weren't found, the service would not start and an error would be logged.

**Comment by atoy3731** [comment]
I'll also caveat that with the fact that DCOS was providing the environment variables inside the container for the host's IP and the random port it was assigning to forward to. We'd have to find a similar functionality in OpenShift.

**Comment by joshua-rutherford** [comment]
@chrisbsmith lets discuss this today when you have time.  I want to ensure that we tackle this is a way that makes the most sense across multiple environments.  I think @atoy3731's suggestion is probably about right, though I don't see why we need to have a `docker.enabled` configuration option at all.  If you start the process and the variables are set use them, if not continue to behave as we currently do.  This does not result in fail fast behavior in the event that someone meant to use the env's but forgot to set them, but with the above suggestion the fail fast behavior only occurs if you set the `docker.enabled` configuration setting anyway.  I just do see that as a surefire solution.

**Comment by joshua-rutherford** [comment]
@ghershfield can you look at this and work into your schedule?

**Comment by atoy3731** [comment]
@joshua-rutherford this approach sounds fine to me.

**Comment by ghershfield** [comment]
I submit that we add parameters to the parameters config. Seems hacky to be defining ms configuration in both parameters.conf && in env.

-com.deciphernow.container.ip.address=
-com.deciphernow.container.port.admin=
-com.deciphernow.container.port.https=
-com.deciphernow.container.port.http=
-com.deciphernow.container.port.thrift=

If set these attributes are sent to discovery. Otherwise default to the current configuration.

**Comment by chrisbsmith** [comment]
Lets discuss this more, but we wouldn't be setting the environment variables, rather DC/OS or OpenShift or Kubernetes injects variables into the container at runtime. 

For Kubernetes the variables are `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`

**Comment by joshua-rutherford** [comment]
@ghershfield, I agree that it is an added level of indirection, but it is actually required since the different container management tools may inject different variables as @chrisbsmith has said. I think the set you need will be something like:

```
// these define the environment variables that should contain the ip address or ports.
// if set these take presedence over any other configurations and we fail fast if any 
// of environment variables listed are not set in the environment
-com.deciphernow.container.ip.address.env=
-com.deciphernow.container.port.admin.env=
-com.deciphernow.container.port.https.env=
-com.deciphernow.container.port.http.env=
-com.deciphernow.container.port.thrift.env=

// these behave as they currently do (i.e., take presendence over defaults)
-com.deciphernow.container.ip.address=
-com.deciphernow.container.port.admin=
-com.deciphernow.container.port.https=
-com.deciphernow.container.port.http=
-com.deciphernow.container.port.thrift=
```

Does that make sense @chrisbsmith and @ghershfield

**Comment by justincely** [comment]
For the env vars - what if the code looked both in the environment and a config file for these (and other) settings in a sort of cascading operations.  1) check environment, and use if there 2) use config file.  

That way we could launch these services in openshift and inject environment variables at runtime. e.g. in an openshift `json` config:
```json
            "env": [
              {
                "name": "COM-DECIPHERNOW-CONTAINER-IP-ADDRESS",
                "value": "$OPENSHIFT_CARTNAME_IP"
              }
            ],
```

**Comment by joshua-rutherford** [comment]
That's what we are planning on doing.  ENV -> Config -> Defaults

**Comment by joshua-rutherford** [comment]
@ghershfield, made a good point offline just now so I'm capturing for posterity.  we need to capture internal service binding ports (i.e., the ports the service binds to) and the external service binding ports (i.e., the ports that the host forwards from).  I'm curious as to our requirement to set both of these from ENV's.  In other words,  do we want to support random port assignments (container and host) here?  

For example, DCOS supports randomized port assignments by defining the mapping like:

```
"ports": [0, 0, 0, 0]
```

This will result in random host ports and container ports being assigned.  In this mode, we'd have to accept the random container port assignments via ENV (i.e., via the variables `$PORT0`, `$PORT1`, `$PORT2` and `$PORT3`).  However the documentation is clear that I cannot get the random container ports via an environment variable ("Note that only host ports are made available to a task through environment variables.").  This is makes this entirely unusable unless I misunderstand: https://dcos.io/docs/1.7/usage/marathon/ports/

Or we can define static container ports and random host ports with:

```
"ports": [2000, 2001, 2002, 2003]
```

This will result in random host ports being mapped to container ports 2000, 2001, 2002 and 2003.  In this mode, we'd have to accept the random container port assignments via ENV (i.e., via the variables `$PORT0`, `$PORT1`, `$PORT2` and `$PORT3`).  In this case I don't need to modify the container port bindings.

Lastly, we can specify both host and container ports with:

```
    "ports": [
        2001, 2002, 3000
    ],
    "requirePorts" : true
```

This is a huge constraint though as DCOS has to manage port collisions (not good).

**Comment by joshua-rutherford** [comment]
I'm going to go ahead an make an executive decision here and say 
![image](https://user-images.githubusercontent.com/5482080/31452493-1087baf2-ae7d-11e7-8818-f74421fe7f6c.png). I think this is the most robust way to handle this and thus probably the best.

To be clear there will be two sets of configurations, binding configurations and announcing configurations.  So we have:

```
// these define the environment variables that should contain the ports to which the service
// should bind if these are not set we will fall back to the config settings below then the defaults.
-com.deciphernow.server.config.admin.port.env=
-com.deciphernow.server.config.rest.httpPort.env=
-com.deciphernow.server.config.rest.httpsPort.env=
-com.deciphernow.server.config.thrift.port.env=

// these behave as they currently do (i.e., take precendence over defaults)
-com.deciphernow.server.config.admin.port=
-com.deciphernow.server.config.rest.httpPort=
-com.deciphernow.server.config.rest.httpsPort=
-com.deciphernow.server.config.thrift.port=

// these define the environment variables that should contain the ports to which the service
// should announce if these are not set we will fall back to the config settings below then to
// the `server` settings, environment variables or defaults (in that order).
-com.deciphernow.announcement.config.ip.address.env=
-com.deciphernow.announcement.config.admin.port=
-com.deciphernow.announcement.config.rest.httpPort=
-com.deciphernow.announcement.config.rest.httpsPort=
-com.deciphernow.announcement.config.thrift.port=

// these behave as they currently do (i.e., take precedence over defaults)
-com.deciphernow.announcement.config.ip.address.env=
-com.deciphernow.announcement.config.admin.port.env=
-com.deciphernow.announcement.config.rest.httpPort.env=
-com.deciphernow.announcement.config.rest.httpsPort.env=
-com.deciphernow.announcement.config.thrift.port.env=
```

**Comment by johntrollinger** [comment]
Guys, 
In talking with the ADX folks Openshift (or maybe Kubernetes) does not expose IP address but only a routable hostname.  not sure how this might change your approach.

**Comment by joshua-rutherford** [comment]
That is a fair point, perhaps renaming to `...config.host` makes more sense?  In the end, I don't think it matters as we should simply advertise as the string value of that env or config item.
