### ISSUE TITLE
admin/shutdown method not working due to GET instead of Post

### ISSUE THREAD

**Issue by studerw** [DecipherNow/gm-fabric-jvm#70]
click on the 'shutdown' on the admin pages sends a GET, not a post. This is happening in 0.2.1, not sure about latest master.

See Screenshots

![image](https://user-images.githubusercontent.com/6321283/32392455-351ff17c-c0ac-11e7-829e-715f6be99e3b.png)

![image](https://user-images.githubusercontent.com/6321283/32392447-25eabae8-c0ac-11e7-8aae-8fcfaf840cac.png)

**Comment by ghershfield** [comment]
We are not modifying the twitter code to fix this.

**Comment by studerw** [comment]
Please keep actual bugs open until they're fixed. Or have CHolmes himself close this.
