### ISSUE TITLE
Maven central frowns upon <repositories> and <pluginRepositories>.

### ISSUE THREAD

**Issue by joshua-rutherford** [DecipherNow/gm-fabric-jvm#8]
As per the requirements [here](http://central.sonatype.org/pages/requirements.html), if we intend to have our project hosted on Maven Central the custom repository settings are discouraged.  I have built this project twice after deleting my local repository.  The first time was with default settings (i.e., no `~/.m2/settings.xml` and once with the internal Archiva artifact repository.  In both cases, the project built fine.  

@ghershfield, I know you've discussed this with me before but can you give me an overview of why these are needed and confirm if they still are?

**Comment by ghershfield** [comment]
The issue is that Maven Central DOES NOT contain all the required dependencies on older Twitter libs. It appeared as if they have everything for the latest 2 lib sets, but anything older they were missing dependencies.
